database : LSVQ
model_name : DualRes-VQA
lr : 1e-5
decay_ratio : 0.90
decay : 2
seed : 3407
batch_size : 16
num_workers : 8
resize : 256
crop_size : 224
epochs : 30
rounds : 10
ops_candidates : ['concat', 'add', 'attn','mul','modulate']
multi_gpu : store_true
gpu_ids : [0,1]
loss_type : plcc
use_ddp : True
trained_model_path : your_path
save_model_path : your_path
log_path : your_path
datainfo_train : your_path
datainfo_val : your_path
datainfo_test : your_path
datainfo_test_1080p : your_path
videos_path : your_path
saliency_path : your_path
slowfast_path : your_path